#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace podiumTimeModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PodiumTime")]
	public partial class podiumTimeClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInscricao(Inscricao instance);
    partial void UpdateInscricao(Inscricao instance);
    partial void DeleteInscricao(Inscricao instance);
    #endregion
		
		public podiumTimeClassesDataContext() : 
				base(global::podiumTimeModels.Properties.Settings.Default.PodiumTimeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public podiumTimeClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public podiumTimeClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public podiumTimeClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public podiumTimeClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Inscricao> Inscricaos
		{
			get
			{
				return this.GetTable<Inscricao>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inscricao")]
	public partial class Inscricao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _DataInscricao;
		
		private string _Nome;
		
		private string _Sexo;
		
		private string _Email;
		
		private string _Equipa;
		
		private string _TipoInscricao;
		
		private string _DocIdentificacao;
		
		private string _Contacto;
		
		private System.Nullable<int> _Dorsal;
		
		private System.Nullable<bool> _Pago;
		
		private string _TamanhoJersey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDataInscricaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataInscricaoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEquipaChanging(string value);
    partial void OnEquipaChanged();
    partial void OnTipoInscricaoChanging(string value);
    partial void OnTipoInscricaoChanged();
    partial void OnDocIdentificacaoChanging(string value);
    partial void OnDocIdentificacaoChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    partial void OnDorsalChanging(System.Nullable<int> value);
    partial void OnDorsalChanged();
    partial void OnPagoChanging(System.Nullable<bool> value);
    partial void OnPagoChanged();
    partial void OnTamanhoJerseyChanging(string value);
    partial void OnTamanhoJerseyChanged();
    #endregion
		
		public Inscricao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInscricao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataInscricao
		{
			get
			{
				return this._DataInscricao;
			}
			set
			{
				if ((this._DataInscricao != value))
				{
					this.OnDataInscricaoChanging(value);
					this.SendPropertyChanging();
					this._DataInscricao = value;
					this.SendPropertyChanged("DataInscricao");
					this.OnDataInscricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(450)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="NVarChar(450)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(450)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipa", DbType="NVarChar(450)")]
		public string Equipa
		{
			get
			{
				return this._Equipa;
			}
			set
			{
				if ((this._Equipa != value))
				{
					this.OnEquipaChanging(value);
					this.SendPropertyChanging();
					this._Equipa = value;
					this.SendPropertyChanged("Equipa");
					this.OnEquipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoInscricao", DbType="NVarChar(450)")]
		public string TipoInscricao
		{
			get
			{
				return this._TipoInscricao;
			}
			set
			{
				if ((this._TipoInscricao != value))
				{
					this.OnTipoInscricaoChanging(value);
					this.SendPropertyChanging();
					this._TipoInscricao = value;
					this.SendPropertyChanged("TipoInscricao");
					this.OnTipoInscricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocIdentificacao", DbType="NVarChar(450)")]
		public string DocIdentificacao
		{
			get
			{
				return this._DocIdentificacao;
			}
			set
			{
				if ((this._DocIdentificacao != value))
				{
					this.OnDocIdentificacaoChanging(value);
					this.SendPropertyChanging();
					this._DocIdentificacao = value;
					this.SendPropertyChanged("DocIdentificacao");
					this.OnDocIdentificacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="NVarChar(450)")]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dorsal", DbType="Int")]
		public System.Nullable<int> Dorsal
		{
			get
			{
				return this._Dorsal;
			}
			set
			{
				if ((this._Dorsal != value))
				{
					this.OnDorsalChanging(value);
					this.SendPropertyChanging();
					this._Dorsal = value;
					this.SendPropertyChanged("Dorsal");
					this.OnDorsalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pago", DbType="Bit")]
		public System.Nullable<bool> Pago
		{
			get
			{
				return this._Pago;
			}
			set
			{
				if ((this._Pago != value))
				{
					this.OnPagoChanging(value);
					this.SendPropertyChanging();
					this._Pago = value;
					this.SendPropertyChanged("Pago");
					this.OnPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamanhoJersey", DbType="NVarChar(450)")]
		public string TamanhoJersey
		{
			get
			{
				return this._TamanhoJersey;
			}
			set
			{
				if ((this._TamanhoJersey != value))
				{
					this.OnTamanhoJerseyChanging(value);
					this.SendPropertyChanging();
					this._TamanhoJersey = value;
					this.SendPropertyChanged("TamanhoJersey");
					this.OnTamanhoJerseyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
